spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: UTF-8
    schema: classpath*:schema.sql
    data: classpath*:data.sql
    continue-on-error: true
    initialization-mode: always #never,always
  freemarker:
    checkTemplateLocation: false
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true